# frozen_string_literal: true

module ForwardedMail
  # A big thanks to Crisp for coding the Javascript initial version
  # https://github.com/crisp-oss/email-forward-parser/blob/master/lib/parser.js (MIT License)
  #
  module Regexps
    BYTE_ORDER_MARK_REGEXP = /\uFEFF/m.freeze # Outlook 2019
    QUOTE_LINE_BREAK_REGEXP = /^(>+)\s?$/m.freeze # Apple Mail, Missive
    QUOTE_REGEXP = /^(>+)\s?/m.freeze # Apple Mail
    FOUR_SPACE_REGEXP = /^(\ {4})\s?/m.freeze # Outlook 2019

    # rubocop:disable Layout/LineLength
    SEPARATOR_REGEXPS = [
      /^>?\s*Begin forwarded message\s?:/m, #Apple Mail (en)
      /^>?\s*Začátek přeposílané zprávy\s?:/m, #Apple Mail (cs)
      /^>?\s*Start på videresendt besked\s?:/m, #Apple Mail (da)
      /^>?\s*Anfang der weitergeleiteten Nachricht\s?:/m, #Apple Mail (de)
      /^>?\s*Inicio del mensaje reenviado\s?:/m, #Apple Mail (es)
      /^>?\s*Välitetty viesti alkaa\s?:/m, #Apple Mail (fi)
      /^>?\s*Début du message réexpédié\s?:/m, #Apple Mail (fr)
      /^>?\s*Début du message transféré\s?:/m, #Apple Mail iOS (fr)
      /^>?\s*Započni proslijeđenu poruku\s?:/m, #Apple Mail (hr)
      /^>?\s*Továbbított levél kezdete\s?:/m, #Apple Mail (hu)
      /^>?\s*Inizio messaggio inoltrato\s?:/m, #Apple Mail (it)
      /^>?\s*Begin doorgestuurd bericht\s?:/m, #Apple Mail (nl)
      /^>?\s*Videresendt melding\s?:/m, #Apple Mail (no)
      /^>?\s*Początek przekazywanej wiadomości\s?:/m, #Apple Mail (pl)
      /^>?\s*Início da mensagem reencaminhada\s?:/m, #Apple Mail (pt)
      /^>?\s*Início da mensagem encaminhada\s?:/m, #Apple Mail (pt-br)
      /^>?\s*Începe mesajul redirecționat\s?:/m, #Apple Mail (ro)
      /^>?\s*Начало переадресованного сообщения\s?:/m, #Apple Mail (ro)
      /^>?\s*Začiatok preposlanej správy\s?:/m, #Apple Mail (sk)
      /^>?\s*Vidarebefordrat mejl\s?:/m, #Apple Mail (sv)
      /^>?\s*İleti başlangıcı\s?:/m, #Apple Mail (tr)
      /^>?\s*Початок листа, що пересилається\s?:/m, #Apple Mail (uk)
      /^\s*-{8,10}\s*Forwarded message\s*-{8,10}\s*/m, #Gmail (all locales), Missive (en), HubSpot (en)
      /^\s*_{32}\s*$/m, #Outlook Live / 365 (all locales)
      /^\s?Dne\s?.+\,\s?.+\s*[\[|<].+[\]|>]\s?napsal\(a\)\s?:/m, #Outlook 2019 (cz)
      /^\s?D.\s?.+\s?skrev\s?\".+\"\s*[\[|<].+[\]|>]\s?:/m, #Outlook 2019 (da)
      /^\s?Am\s?.+\s?schrieb\s?\".+\"\s*[\[|<].+[\]|>]\s?:/m, #Outlook 2019 (de)
      /^\s?On\s?.+\,\s?\".+\"\s*[\[|<].+[\]|>]\s?wrote\s?:/m, #Outlook 2019 (en)
      /^\s?El\s?.+\,\s?\".+\"\s*[\[|<].+[\]|>]\s?escribió\s?:/m, #Outlook 2019 (es)
      /^\s?Le\s?.+\,\s?«.+»\s*[\[|<].+[\]|>]\s?a écrit\s?:/m, #Outlook 2019 (fr)
      /^\s?.+\s*[\[|<].+[\]|>]\s?kirjoitti\s?.+\s?:/m, #Outlook 2019 (fi)
      /^\s?.+\s?időpontban\s?.+\s*[\[|<|(].+[\]|>|)]\s?ezt írta\s?:/m, #Outlook 2019 (hu)
      /^\s?Il giorno\s?.+\s?\".+\"\s*[\[|<].+[\]|>]\s?ha scritto\s?:/m, #Outlook 2019 (it)
      /^\s?Op\s?.+\s?heeft\s?.+\s*[\[|<].+[\]|>]\s?geschreven\s?:/m, #Outlook 2019 (nl)
      /^\s?.+\s*[\[|<].+[\]|>]\s?skrev følgende den\s?.+\s?:/m, #Outlook 2019 (no)
      /^\s?Dnia\s?.+\s?„.+”\s*[\[|<].+[\]|>]\s?napisał\s?:/m, #Outlook 2019 (pl)
      /^\s?Em\s?.+\,\s?\".+\"\s*[\[|<].+[\]|>]\s?escreveu\s?:/m, #Outlook 2019 (pt)
      /^\s?.+\s?пользователь\s?\".+\"\s*[\[|<].+[\]|>]\s?написал\s?:/m, #Outlook 2019 (ru)
      /^\s?.+\s?používateľ\s?.+\s*\([\[|<].+[\]|>]\)\s?napísal\s?:/m, #Outlook 2019 (sk)
      /^\s?Den\s?.+\s?skrev\s?\".+\"\s*[\[|<].+[\]|>]\s?följande\s?:/m, #Outlook 2019 (sv)
      /^\s?\".+\"\s*[\[|<].+[\]|>]\,\s?.+\s?tarihinde şunu yazdı\s?:/m, #Outlook 2019 (tr)
      /^\s*-{5,8} Přeposlaná zpráva -{5,8}\s*/m, #Yahoo Mail (cs), Thunderbird (cs)
      /^\s*-{5,8} Videresendt meddelelse -{5,8}\s*/m, #Yahoo Mail (da), Thunderbird (da)
      /^\s*-{5,10} Weitergeleitete Nachricht -{5,10}\s*/m, #Yahoo Mail (de), Thunderbird (de), HubSpot (de)
      /^\s*-{5,8} Forwarded Message -{5,8}\s*/m, #Yahoo Mail (en), Thunderbird (en)
      /^\s*-{5,10} Mensaje reenviado -{5,10}\s*/m, #Yahoo Mail (es), Thunderbird (es), HubSpot (es)
      /^\s*-{5,10} Edelleenlähetetty viesti -{5,10}\s*/m, #Yahoo Mail (fi), HubSpot (fi)
      /^\s*-{5} Message transmis -{5}\s*/m, #Yahoo Mail (fr)
      /^\s*-{5,8} Továbbított üzenet -{5,8}\s*/m, #Yahoo Mail (hu), Thunderbird (hu)
      /^\s*-{5,10} Messaggio inoltrato -{5,10}\s*/m, #Yahoo Mail (it), HubSpot (it)
      /^\s*-{5,10} Doorgestuurd bericht -{5,10}\s*/m, #Yahoo Mail (nl), Thunderbird (nl), HubSpot (nl)
      /^\s*-{5,8} Videresendt melding -{5,8}\s*/m, #Yahoo Mail (no), Thunderbird (no)
      /^\s*-{5} Przekazana wiadomość -{5}\s*/m, #Yahoo Mail (pl)
      /^\s*-{5,8} Mensagem reencaminhada -{5,8}\s*/m, #Yahoo Mail (pt), Thunderbird (pt)
      /^\s*-{5,10} Mensagem encaminhada -{5,10}\s*/m, #Yahoo Mail (pt-br), Thunderbird (pt-br), HubSpot (pt-br)
      /^\s*-{5,8} Mesaj redirecționat -{5,8}\s*/m, #Yahoo Mail (ro)
      /^\s*-{5} Пересылаемое сообщение -{5}\s*/m, #Yahoo Mail (ru)
      /^\s*-{5} Preposlaná správa -{5}\s*/m, #Yahoo Mail (sk)
      /^\s*-{5,10} Vidarebefordrat meddelande -{5,10}\s*/m, #Yahoo Mail (sv), Thunderbird (sv), HubSpot (sv)
      /^\s*-{5} İletilmiş Mesaj -{5}\s*/m, #Yahoo Mail (tr)
      /^\s*-{5} Перенаправлене повідомлення -{5}\s*/m, #Yahoo Mail (uk)
      /^\s*-{8} Välitetty viesti \/ Fwd.Msg -{8}\s*/m, #Thunderbird (fi)
      /^\s*-{8,10} Message transféré -{8,10}\s*/m, #Thunderbird (fr), HubSpot (fr)
      /^\s*-{8} Proslijeđena poruka -{8}\s*/m, #Thunderbird (hr)
      /^\s*-{8} Messaggio Inoltrato -{8}\s*/m, #Thunderbird (it)
      /^\s*-{3} Treść przekazanej wiadomości -{3}\s*/m, #Thunderbird (pl)
      /^\s*-{8} Перенаправленное сообщение -{8}\s*/m, #Thunderbird (ru)
      /^\s*-{8} Preposlaná správa --- Forwarded Message -{8}\s*/m, #Thunderbird (sk)
      /^\s*-{8} İletilen İleti -{8}\s*/m, #Thunderbird (tr)
      /^\s*-{8} Переслане повідомлення -{8}\s*/m, #Thunderbird (uk)
      /^\s*-{9,10} メッセージを転送 -{9,10}\s*/m, #HubSpot (ja)
      /^\s*-{9,10} Wiadomość przesłana dalej -{9,10}\s*/m, #HubSpot (pl)
      /^>?\s*-{10} Original Message -{10}\s*/m #IONOS by 1 & 1 (en)
    ]

    SUBJECT_REGEXPS = [
      /^Fw:(.*)/m, # Outlook Live / 365 (cs, en, hr, hu, sk), Yahoo Mail (all locales)
      /^VS:(.*)/m, # Outlook Live / 365 (da), New Outlook 2019 (da)
      /^WG:(.*)/m, # Outlook Live / 365 (de), New Outlook 2019 (de)
      /^RV:(.*)/m, # Outlook Live / 365 (es), New Outlook 2019 (es)
      /^TR:(.*)/m, # Outlook Live / 365 (fr), New Outlook 2019 (fr)
      /^I:(.*)/m, # Outlook Live / 365 (it), New Outlook 2019 (it)
      /^FW:(.*)/m, # Outlook Live / 365 (nl, pt), New Outlook 2019 (cs, en, hu, nl, pt, ru, sk), Outlook 2019 (all locales)
      /^Vs:(.*)/m, # Outlook Live / 365 (no)
      /^PD:(.*)/m, # Outlook Live / 365 (pl), New Outlook 2019 (pl)
      /^ENC:(.*)/m, # Outlook Live / 365 (pt-br), New Outlook 2019 (pt-br)
      /^Redir.:(.*)/m, # Outlook Live / 365 (ro)
      /^VB:(.*)/m, # Outlook Live / 365 (sv), New Outlook 2019 (sv)
      /^VL:(.*)/m, # New Outlook 2019 (fi)
      /^Videresend:(.*)/m, # New Outlook 2019 (no)
      /^İLT:(.*)/m, # New Outlook 2019 (tr)
      /^Fwd:(.*)/m # Gmail (all locales), Thunderbird (all locales), Missive (en)
    ].freeze

    FROM_REGEXPS = [
      /^(\*?\s*From\s?:\*?(.+))$/, # Apple Mail (en), Outlook Live / 365 (all locales), New Outlook 2019 (en), Thunderbird (da, en), Missive (en), HubSpot (en)
      /^(\s*Od\s?:(.+))$/, # Apple Mail (cs, pl, sk), Gmail (cs, pl, sk), New Outlook 2019 (cs, pl, sk), Thunderbird (cs, sk), HubSpot (pl)
      /^(\s*Fra\s?:(.+))$/, # Apple Mail (da, no), Gmail (da, no), New Outlook 2019 (da), Thunderbird (no)
      /^(\s*Von\s?:(.+))$/, # Apple Mail (de), Gmail (de), New Outlook 2019 (de), Thunderbird (de), HubSpot (de)
      /^(\s*De\s?:(.+))$/, # Apple Mail (es, fr, pt, pt-br), Gmail (es, fr, pt, pt-br), New Outlook 2019 (es, fr, pt, pt-br), Thunderbird (fr, pt, pt-br), HubSpot (es, fr, pt-br)
      /^(\s*Lähettäjä\s?:(.+))$/, # Apple Mail (fi), Gmail (fi), New Outlook 2019 (fi), Thunderbird (fi), HubSpot (fi)
      /^(\s*Šalje\s?:(.+))$/, # Apple Mail (hr), Gmail (hr), Thunderbird (hr)
      /^(\s*Feladó\s?:(.+))$/, # Apple Mail (hu), Gmail (hu), New Outlook 2019 (fr), Thunderbird (hu)
      /^(\s*Da\s?:(.+))$/, # Apple Mail (it), Gmail (it), New Outlook 2019 (it), HubSpot (it)
      /^(\s*Van\s?:(.+))$/, # Apple Mail (nl), Gmail (nl), New Outlook 2019 (nl), Thunderbird (nl), HubSpot (nl)
      /^(\s*Expeditorul\s?:(.+))$/, # Apple Mail (ro)
      /^(\s*Отправитель\s?:(.+))$/, # Apple Mail (ru)
      /^(\s*Från\s?:(.+))$/, # Apple Mail (sv), Gmail (sv), New Outlook 2019 (sv), Thunderbird (sv), HubSpot (sv)
      /^(\s*Kimden\s?:(.+))$/, # Apple Mail (tr), Thunderbird (tr)
      /^(\s*Від кого\s?:(.+))$/, # Apple Mail (uk)
      /^(\s*Saatja\s?:(.+))$/, # Gmail (et)
      /^(\s*De la\s?:(.+))$/, # Gmail (ro)
      /^(\s*Gönderen\s?:(.+))$/, # Gmail (tr)
      /^(\s*От\s?:(.+))$/, # Gmail (ru), New Outlook 2019 (ru), Thunderbird (ru)
      /^(\s*Від\s?:(.+))$/, # Gmail (uk), Thunderbird (uk)
      /^(\s*Mittente\s?:(.+))$/, # Thunderbird (it)
      /^(\s*Nadawca\s?:(.+))$/, # Thunderbird (pl)
      /^(\s*de la\s?:(.+))$/, # Thunderbird (ro)
      /^(\s*送信元：(.+))$/ # HubSpot (ja)
    ].freeze

    FROM_LAX_REGEXPS = [
      /(\s*From\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (en)
      /(\s*Od\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (cs, pl, sk)
      /(\s*Fra\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (da, no)
      /(\s*Von\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (de)
      /(\s*De\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (es, fr, pt, pt-br)
      /(\s*Lähettäjä\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (fi)
      /(\s*Feladó\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (hu)
      /(\s*Da\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (it)
      /(\s*Van\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (nl)
      /(\s*De la\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (ro)
      /(\s*От\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (ru)
      /(\s*Från\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (sv)
      /(\s*Kimden\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/, # Yahoo Mail (tr)
      /(\s*Від\s?:(.+?)\s?\n?\s*[\[|<](.+?)[\]|>])/ # Yahoo Mail (uk)
    ].freeze

    MAILBOX_REGEXP = [
      /^\s?\n?\s*<.+?<mailto:(.+?)>>/, # "<walter.sheltan@acme.com<mailto:walter.sheltan@acme.com>>"
      /^(.+?)\s?\n?\s*<.+?<mailto:(.+?)>>/, # "Walter Sheltan <walter.sheltan@acme.com<mailto:walter.sheltan@acme.com>>"
      /^(.+?)\s?\n?\s*[\[|<]mailto:(.+?)[\]|>]/, # "Walter Sheltan <mailto:walter.sheltan@acme.com>" or "Walter Sheltan [mailto:walter.sheltan@acme.com]" or "walter.sheltan@acme.com <mailto:walter.sheltan@acme.com>"
      /^'(.+?)'\s?\n?\s*[\[|<](.+?)[\]|>]/, # "'Walter Sheltan' <walter.sheltan@acme.com>" or "'Walter Sheltan' [walter.sheltan@acme.com]" or "'walter.sheltan@acme.com' <walter.sheltan@acme.com>"
      /^"'(.+?)'"\s?\n?\s*[\[|<](.+?)[\]|>]/, # ""'Walter Sheltan'" <walter.sheltan@acme.com>" or ""'Walter Sheltan'" [walter.sheltan@acme.com]" or ""'walter.sheltan@acme.com'" <walter.sheltan@acme.com>"
      /^"(.+?)"\s?\n?\s*[\[|<](.+?)[\]|>]/, # ""Walter Sheltan" <walter.sheltan@acme.com>" or ""Walter Sheltan" [walter.sheltan@acme.com]" or ""walter.sheltan@acme.com" <walter.sheltan@acme.com>"
      /^([^,;]+?)\s?\n?\s*[\[|<](.+?)[\]|>]/, # "Walter Sheltan <walter.sheltan@acme.com>" or "Walter Sheltan [walter.sheltan@acme.com]" or "walter.sheltan@acme.com <walter.sheltan@acme.com>"
      /^(.?)\s?\n?\s*[\[|<](.+?)[\]|>]/, # "<walter.sheltan@acme.com>"
      /^([^\s@]+@[^\s@]+\.[^\s@,]+)/, # "walter.sheltan@acme.com"
      /^([^;].+?)\s?\n?\s*[\[|<](.+?)[\]|>]/ # "Walter, Sheltan <walter.sheltan@acme.com>" or "Walter, Sheltan [walter.sheltan@acme.com]"
    ].freeze

    ORIGINAL_SUBJECT_REGEXPS = [
      /^\*?Subject\s?:\*?.+$/i, # Apple Mail (en), Gmail (all locales), Outlook Live / 365 (all locales), New Outlook 2019 (en), Thunderbird (da, en), Missive (en), HubSpot (en)
      /^Předmět\s?:.+$/i, # Apple Mail (cs), New Outlook 2019 (cs), Thunderbird (cs)
      /^Emne\s?:.+$/i, # Apple Mail (da, no), New Outlook 2019 (da), Thunderbird (no)
      /^Betreff\s?:.+$/i, # Apple Mail (de), New Outlook 2019 (de), Thunderbird (de), HubSpot (de)
      /^Asunto\s?:.+$/i, # Apple Mail (es), New Outlook 2019 (es), Thunderbird (es), HubSpot (es)
      /^Aihe\s?:.+$/i, # Apple Mail (fi), New Outlook 2019 (fi), Thunderbird (fi), HubSpot (fi)
      /^Objet\s?:.+$/i, # Apple Mail (fr), New Outlook 2019 (fr), HubSpot (fr)
      /^Predmet\s?:.+$/i, # Apple Mail (hr, sk), New Outlook 2019 (sk), Thunderbird (sk)
      /^Tárgy\s?:.+$/i, # Apple Mail (hu), New Outlook 2019 (hu), Thunderbird (hu)
      /^Oggetto\s?:.+$/i, # Apple Mail (it), New Outlook 2019 (it), Thunderbird (it), HubSpot (it)
      /^Onderwerp\s?:.+$/i, # Apple Mail (nl), New Outlook 2019 (nl), Thunderbird (nl), HubSpot (nl)
      /^Temat\s?:.+$/i, # Apple Mail (pl), New Outlook 2019 (pl), Thunderbird (pl), HubSpot (pl)
      /^Assunto\s?:.+$/i, # Apple Mail (pt, pt-br), New Outlook 2019 (pt, pt-br), Thunderbird (pt, pt-br), HubSpot (pt-br)
      /^Subiectul\s?:.+$/i, # Apple Mail (ro), Thunderbird (ro)
      /^Тема\s?:.+$/i, # Apple Mail (ru, uk), New Outlook 2019 (ru), Thunderbird (ru, uk)
      /^Ämne\s?:.+$/i, # Apple Mail (sv), New Outlook 2019 (sv), Thunderbird (sv), HubSpot (sv)
      /^Konu\s?:.+$/i, # Apple Mail (tr), Thunderbird (tr)
      /^Sujet\s?:.+$/i, # Thunderbird (fr)
      /^Naslov\s?:.+$/i, # Thunderbird (hr)
      /^件名：.+$/i, # HubSpot (ja)
    ].freeze

    ORIGINAL_FROM_REGEXPS = [
      /^(\*?\s*From\s?:\*?.+)$/, # Apple Mail (en), Outlook Live / 365 (all locales), New Outlook 2019 (en), Thunderbird (da, en), Missive (en), HubSpot (en)
      /^(\s*Od\s?:.+)$/, # Apple Mail (cs, pl, sk), Gmail (cs, pl, sk), New Outlook 2019 (cs, pl, sk), Thunderbird (cs, sk), HubSpot (pl)
      /^(\s*Fra\s?:.+)$/, # Apple Mail (da, no), Gmail (da, no), New Outlook 2019 (da), Thunderbird (no)
      /^(\s*Von\s?:.+)$/, # Apple Mail (de), Gmail (de), New Outlook 2019 (de), Thunderbird (de), HubSpot (de)
      /^(\s*De\s?:.+)$/, # Apple Mail (es, fr, pt, pt-br), Gmail (es, fr, pt, pt-br), New Outlook 2019 (es, fr, pt, pt-br), Thunderbird (fr, pt, pt-br), HubSpot (es, fr, pt-br)
      /^(\s*Lähettäjä\s?:.+)$/, # Apple Mail (fi), Gmail (fi), New Outlook 2019 (fi), Thunderbird (fi), HubSpot (fi)
      /^(\s*Šalje\s?:.+)$/, # Apple Mail (hr), Gmail (hr), Thunderbird (hr)
      /^(\s*Feladó\s?:.+)$/, # Apple Mail (hu), Gmail (hu), New Outlook 2019 (fr), Thunderbird (hu)
      /^(\s*Da\s?:.+)$/, # Apple Mail (it), Gmail (it), New Outlook 2019 (it), HubSpot (it)
      /^(\s*Van\s?:.+)$/, # Apple Mail (nl), Gmail (nl), New Outlook 2019 (nl), Thunderbird (nl), HubSpot (nl)
      /^(\s*Expeditorul\s?:.+)$/, # Apple Mail (ro)
      /^(\s*Отправитель\s?:.+)$/, # Apple Mail (ru)
      /^(\s*Från\s?:.+)$/, # Apple Mail (sv), Gmail (sv), New Outlook 2019 (sv), Thunderbird (sv), HubSpot (sv)
      /^(\s*Kimden\s?:.+)$/, # Apple Mail (tr), Thunderbird (tr)
      /^(\s*Від кого\s?:.+)$/, # Apple Mail (uk)
      /^(\s*Saatja\s?:.+)$/, # Gmail (et)
      /^(\s*De la\s?:.+)$/, # Gmail (ro)
      /^(\s*Gönderen\s?:.+)$/, # Gmail (tr)
      /^(\s*От\s?:.+)$/, # Gmail (ru), New Outlook 2019 (ru), Thunderbird (ru)
      /^(\s*Від\s?:.+)$/, # Gmail (uk), Thunderbird (uk)
      /^(\s*Mittente\s?:.+)$/, # Thunderbird (it)
      /^(\s*Nadawca\s?:.+)$/, # Thunderbird (pl)
      /^(\s*de la\s?:.+)$/, # Thunderbird (ro)
      /^(\s*送信元：.+)$/ # HubSpot (ja)
    ]

    ORIGINAL_TO_REGEXPS = [
      /^\*?\s*To\s?:\*?.+$/, # Apple Mail (en), Gmail (all locales), Outlook Live / 365 (all locales), Thunderbird (da, en), Missive (en), HubSpot (en)
      /^\s*Komu\s?:.+$/, # Apple Mail (cs), New Outlook 2019 (cs, sk), Thunderbird (cs)
      /^\s*Til\s?:.+$/, # Apple Mail (da, no), New Outlook 2019 (da), Thunderbird (no)
      /^\s*An\s?:.+$/, # Apple Mail (de), New Outlook 2019 (de), Thunderbird (de), HubSpot (de)
      /^\s*Para\s?:.+$/, # Apple Mail (es, pt, pt-br), New Outlook 2019 (es, pt, pt-br), Thunderbird (es, pt, pt-br), HubSpot (pt-br)
      /^\s*Vastaanottaja\s?:.+$/, # Apple Mail (fi), New Outlook 2019 (fi), Thunderbird (fi), HubSpot (fi)
      /^\s*À\s?:.+$/, # Apple Mail (fr), New Outlook 2019 (fr), HubSpot (fr)
      /^\s*Prima\s?:.+$/, # Apple Mail (hr), Thunderbird (hr)
      /^\s*Címzett\s?:.+$/, # Apple Mail (hu), New Outlook 2019 (hu), Thunderbird (hu)
      /^\s*A\s?:.+$/, # Apple Mail (it), New Outlook 2019 (it), Thunderbird (it), HubSpot (es, it)
      /^\s*Aan\s?:.+$/, # Apple Mail (nl), New Outlook 2019 (nl), Thunderbird (nl), HubSpot (nl)
      /^\s*Do\s?:.+$/, # Apple Mail (pl), New Outlook 2019 (pl), HubSpot (pl)
      /^\s*Destinatarul\s?:.+$/, # Apple Mail (ro)
      /^\s*Кому\s?:.+$/, # Apple Mail (ru, uk), New Outlook 2019 (ru), Thunderbird (ru, uk)
      /^\s*Pre\s?:.+$/, # Apple Mail (sk), Thunderbird (sk)
      /^\s*Till\s?:.+$/, # Apple Mail (sv), New Outlook 2019 (sv), Thunderbird (sv)
      /^\s*Kime\s?:.+$/, # Apple Mail (tr), Thunderbird (tr)
      /^\s*Pour\s?:.+$/, # Thunderbird (fr)
      /^\s*Adresat\s?:.+$/, # Thunderbird (pl)
      /^\s*送信先：.+$/m # HubSpot (ja)
    ]

    ORIGINAL_REPLY_TO_REGEXPS = [
      /^\s*Reply-To\s?:.+$/, # Apple Mail (en)
      /^\s*Odgovori na\s?:.+$/, # Apple Mail (hr)
      /^\s*Odpověď na\s?:.+$/, # Apple Mail (cs)
      /^\s*Svar til\s?:.+$/, # Apple Mail (da)
      /^\s*Antwoord aan\s?:.+$/, # Apple Mail (nl)
      /^\s*Vastaus\s?:.+$/, # Apple Mail (fi)
      /^\s*Répondre à\s?:.+$/, # Apple Mail (fr)
      /^\s*Antwort an\s?:.+$/, # Apple Mail (de)
      /^\s*Válaszcím\s?:.+$/, # Apple Mail (hu)
      /^\s*Rispondi a\s?:.+$/, # Apple Mail (it)
      /^\s*Svar til\s?:.+$/, # Apple Mail (no)
      /^\s*Odpowiedź-do\s?:.+$/, # Apple Mail (pl)
      /^\s*Responder A\s?:.+$/, # Apple Mail (pt)
      /^\s*Responder a\s?:.+$/, # Apple Mail (pt-br, es)
      /^\s*Răspuns către\s?:.+$/, # Apple Mail (ro)
      /^\s*Ответ-Кому\s?:.+$/, # Apple Mail (ru)
      /^\s*Odpovedať-Pre\s?:.+$/, # Apple Mail (sk)
      /^\s*Svara till\s?:.+$/, # Apple Mail (sv)
      /^\s*Yanıt Adresi\s?:.+$/, # Apple Mail (tr)
      /^\s*Кому відповісти\s?:.+$/ # Apple Mail (uk)
    ]

    ORIGINAL_CC_REGEXPS = [
      /^\*?\s*Cc\s?:\*?.+$/, # Apple Mail (en, da, es, fr, hr, it, pt, pt-br, ro, sk), Gmail (all locales), Outlook Live / 365 (all locales), New Outlook 2019 (da, de, en, fr, it, pt-br), Missive (en), HubSpot (de, en, es, it, nl, pt-br)
      /^\s*CC\s?:.+$/, # New Outlook 2019 (es, nl, pt), Thunderbird (da, en, es, fi, hr, hu, it, nl, no, pt, pt-br, ro, tr, uk)
      /^\s*Kopie\s?:.+$/, # Apple Mail (cs, de, nl), New Outlook 2019 (cs), Thunderbird (cs)
      /^\s*Kopio\s?:.+$/, # Apple Mail (fi), New Outlook 2019 (fi), HubSpot (fi)
      /^\s*Másolat\s?:.+$/, # Apple Mail (hu)
      /^\s*Kopi\s?:.+$/, # Apple Mail (no)
      /^\s*Dw\s?:.+$/, # Apple Mail (pl)
      /^\s*Копия\s?:.+$/, # Apple Mail (ru), New Outlook 2019 (ru), Thunderbird (ru)
      /^\s*Kopia\s?:.+$/, # Apple Mail (sv), New Outlook 2019 (sv), Thunderbird (pl, sv), HubSpot (sv)
      /^\s*Bilgi\s?:.+$/, # Apple Mail (tr)
      /^\s*Копія\s?:.+$/, # Apple Mail (uk),
      /^\s*Másolatot kap\s?:.+$/, # New Outlook 2019 (hu)
      /^\s*Kópia\s?:.+$/, # New Outlook 2019 (sk), Thunderbird (sk)
      /^\s*DW\s?:.+$/, # New Outlook 2019 (pl), HubSpot (pl)
      /^\s*Kopie \(CC\)\s?:.+$/, # Thunderbird (de)
      /^\s*Copie à\s?:.+$/, # Thunderbird (fr)
      /^\s*CC：.+$/ # HubSpot (ja)
    ]

    ORIGINAL_DATE_REGEXPS = [
      /^\s*Date\s?:.+$/, # Apple Mail (en, fr), Gmail (all locales), New Outlook 2019 (en, fr), Thunderbird (da, en, fr), Missive (en), HubSpot (en, fr)
      /^\s*Datum\s?:.+$/, # Apple Mail (cs, de, hr, nl, sv), New Outlook 2019 (cs, de, nl, sv), Thunderbird (cs, de, hr, nl, sv), HubSpot (de, nl, sv)
      /^\s*Dato\s?:.+$/, # Apple Mail (da, no), New Outlook 2019 (da), Thunderbird (no)
      /^\s*Envoyé\s?:.+$/, # New Outlook 2019 (fr)
      /^\s*Fecha\s?:.+$/, # Apple Mail (es), New Outlook 2019 (es), Thunderbird (es), HubSpot (es)
      /^\s*Päivämäärä\s?:.+$/, # Apple Mail (fi), New Outlook 2019 (fi), HubSpot (fi)
      /^\s*Dátum\s?:.+$/, # Apple Mail (hu, sk), New Outlook 2019 (sk), Thunderbird (hu, sk)
      /^\s*Data\s?:.+$/, # Apple Mail (it, pl, pt, pt-br), New Outlook 2019 (it, pl, pt, pt-br), Thunderbird (it, pl, pt, pt-br), HubSpot (it, pl, pt-br)
      /^\s*Dată\s?:.+$/, # Apple Mail (ro), Thunderbird (ro)
      /^\s*Дата\s?:.+$/, # Apple Mail (ru, uk), New Outlook 2019 (ru), Thunderbird (ru, uk)
      /^\s*Tarih\s?:.+$/, # Apple Mail (tr), Thunderbird (tr)
      /^\*?\s*Sent\s?:\*?.+$/, # Outlook Live / 365 (all locales)
      /^\s*Päiväys\s?:.+$/, # Thunderbird (fi)
      /^\s*日付：.+$/ # HubSpot (ja)
    ]
    # rubocop:enable Layout/LineLength
  end
end
